"""add articles table

Revision ID: 04ed52df878f
Revises: 4dabd4e6735f
Create Date: 2025-09-04 14:23:33.582112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ed52df878f'
down_revision: Union[str, Sequence[str], None] = '4dabd4e6735f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('articles_author_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_author_fkey'), 'articles', 'users', ['author'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###
