"""Add doctors,Appointments

Revision ID: 1d78ae5faf17
Revises: 04ed52df878f
Create Date: 2025-09-05 19:18:43.547556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d78ae5faf17'
down_revision: Union[str, Sequence[str], None] = '04ed52df878f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apointment_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'created_at')
    op.drop_column('doctors', 'bio')
    op.drop_table('appointments')
    # ### end Alembic commands ###
